using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace titanZPL {
    public partial class titanZPL {
        public string zpl_data_base64="Cl5YQV5MUk5eTU5ZXk1GTixOXkxIMTAsMTJeTUNZXlBPSV5QVzgxMl5DSTI3CgpeRk82MjAsMTMwMF5HRkEsMDA5NjksMDA5NjksMDE5LEZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDAwMDAwMDAwCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDAwMDAwMDAwCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDAwMDAwMDAwCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDAwMDAwMDAwCkYwMDAwMDAwMDAwMDAxRjgwMDAwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDAwMDAxRjgwMDAwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDAzRjgxRjgzRkMwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDAzRjgxRjgzRkMwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGRkY5RjlGRkYwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGRkY5RjlGRkYwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGRkZGRkZGRkZDMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGRkZGRkZGRkZDMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGMDdGRkZGMEZDMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGMDdGRkZGMEZDMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGQzFGRkZDM0YwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGQzFGRkZDM0YwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGRkZGRkZGRkYwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGRkZGRkZGRkYwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDAzRkZGRkZGRkMwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDAzRkZGRkZGRkMwMDAwMDAwMDBGMDAwMDAwMDAwCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDAwMDAwMDAwCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDAwMDAwMDAwCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDAwMDAwMDAwCkYwMDAwMDAwMDAwMUZGRkZGMDAwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDAwMUZGRkZGMDAwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDAwM0ZGRjlGQzAwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDAwM0ZGRjlGQzAwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDAzRkUxRjg3RkMwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDAzRkUxRjg3RkMwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGRjgxRjgzRkYwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGRjgxRjgzRkYwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGRTAxRjgwM0YwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGRTAxRjgwM0YwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGMDAxRjgwMEYwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDBGMDAxRjgwMEYwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDAwMDAxRjgwMDAwMDAwMDAwMDBGMDAwMDAwMDAwCkYwMDAwMDAwMDAwMDAxRjgwMDAwMDAwMDAwMDBGMEZGREMxQzAwCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMEZGREMxQzAwCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDBDMUUzQzAwCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDBDMUUzQzAwCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDBDMUEyQzAwCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDBDMUI2QzAwCkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGMDBDMUI2QzAwCjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBDMUI2QzAwCjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBDMTlDQzAwCjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBDMTlDQzAwCjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBDMTlDQzAwCjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBDMTg4QzAwCjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwCjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwCjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwCl5ETgpeRlQyMCw3OTBeQ1ZZXkJEMl5GSF9eRkQwMDM4NDA5ODEwNDAwMDBbKT5fMUUwMV8xRDk2MVowMDAwMzAxM18xRFVQU05fMUQyVlk5MTJfMUUwN0JJTjlHTjQuME44TzRFSUtLS0VSHCYgV18wRDMoSVMjK08tHCtBQyZHRDc1S1BfMERfMUVfMDReRlMKCl5GVDE1LDE4M15BME4sMjAsMjReRlZTVE9SRSA4OTE2XkZTCl5GVDE1LDIwMl5BME4sMjAsMjReRlY4NjYzODYxNTkwXkZTCl5GVDE1LDIyMV5BME4sMjAsMjReRlZDVlNeRlMKXkZUMTUsMjQxXkEwTiwyMCwyNF5GVjM4MjEgRUxMSVNPTiBEUklWRSBOT1JUSCBXRVNUXkZTCl5GVDE1LDI2MF5BME4sMjAsMjReRlZBTEJVUVVFUlFVRSAgTk0gODcxMTReRlMKXkZUNjAsMzQxXkEwTiwyNiwzMF5GVkVOUk9VVEVeRlMKXkZUNjAsMzY4XkEwTiwyNiwzMF5GVjQxODk5NzY2MTleRlMKXkZUNjAsMzk2XkEwTiwyNiwzMF5GVkVOUk9VVEVeRlMKXkZUNjAsNDIzXkEwTiwyNiwzMF5GVjEwMSBZRVNMRVIgQVZFXkZTCl5GVDYwLDQ2N15BME4sNDUsNDReRlZTRUFUVExFICBXQSA5ODEwNF5GUwpeRlQzODAsMTkwXkEwTiwzMCwzNF5GVjYgTEJTIF5GUwpeRlQ2NzMsMTk0XkEwTiwyOCwzMl5GViAxIE9GIDFeRlMKXkZUNTAwLDIyOV5BME4sMjIsMjZeRlZEV1Q6IDUsNSw1XkZTCl5GVDYyMCw4OTZeQTBOLDEwMCw3Nl5GViAgIF5GUwpeRk82NzcsODAwXkdCMTIzLDEyMywxMjJeRlMKCl5GVDMwMCw3NzheQlkzXkJDTiwxMDMsTixOLCxBXkZWNDIwOTgxMDReRlMKCl5GVDI5MCw2NTNeQTBOLDgwLDcwXkZWV0EgOTgxIDktMDVeRlMKXkZUMTAsODY0XkEwTiw1Niw1OF5GVlVQUyBHUk9VTkReRlMKXkZUMTAsODk3XkEwTiwyNiwzMF5GVlRSQUNLSU5HICM6IDFaIDJWWSA5MTIgMDMgMDAwMCAzMDEzXkZTCl5GTzAsOTIyXkdCODAwLDQsNF5GUwoKXkZUNzkwLDExOTleQTBOLDIyLDI2XkZWIF5GUwpeRlQxMCwxMTk1XkEwTiwyMiwyNl5GVkJJTExJTkc6IF5GUwpeRlQxMjYsMTE5NV5BME4sMjIsMjZeRlZQL1AgXkZTCl5GVDEwLDEzMTFeQTBOLDIyLDI2XkZWUmVmZXJlbmNlIE5vLjE6IGN2c15GUwpeRlQxMCwxMzMzXkEwTiwyMiwyNl5GVlJlZmVyZW5jZSBOby4yOiB0ZXN0XkZTCl5GVDE1LDMxM15BME4sMjgsMzJeRlZTSElQIFRPOiBeRlMKXkZPMCw3OTdeR0I3OTgsMTQsMTReRlMKCl5GTzAsMTE1N15HQjgwMCwxNCwxNF5GUwoKXkZPMCw1NzZeR0I4MDAsNCw0XkZTCgpeRk8yNDAsNTc2XkdCMywyMjEsM15GUwoKXkZUMTkwLDEzNDheQTBOLDE0LDIwXkZWWE9MIDE2LjA4LjAyICAgICAgICAgIE5WNDUgNzguMEEgMDcvMjAxNl5GUwpeRlQxMDUsMTE0Ml5CWTNeQkNOLDIwMixOLE4sLEFeRlYxWjJWWTkxMjAzMDAwMDMwMTNeRlMKCl5GVDI3MywxMDU2XkEwTiw5NSw3NF5GVlNBTVBMRV5GUwpeRk8xMCwxMF5BRE4sMTIsNl5GRFJlZjE6IGN2c15GUw0KXkZPMTAsMzVeQUROLDEyLDZeRkRSZWYyOiB0ZXN0XkZTDQpeRk8xMCw2MF5BRE4sMTIsNl5GRFJlZjM6IF5GUw0KXkZPMTAsODVeQUROLDEyLDZeRkRSZWY0OiBeRlMNCl5GTzI3NSwxMF5BRE4sMTIsNl5GRFNocERhdGU6IDIwMTYtMDktMjBeRlMNCl5GTzI3NSwzNV5BRE4sMTIsNl5GRENtdERhdGU6IF5GUw0KXkZPMjc1LDYwXkFETiwxMiw2XkZEV2VpZ2h0OiA1LjBeRlMNCl5GTzI3NSw4NV5BRE4sMTIsNl5GRENPRDogMC4wMF5GUw0KXkZPNTQwLDEwXkFETiwxMiw2XkZERGVjbFZhbDogMTAwLjAwXkZTDQpeRk81NDAsMzVeQUROLDEyLDZeRkRCYXNlIENoZzogXkZTDQpeRk81NDAsNjBeQUROLDEyLDZeRkRTdXIgQ2hnOiBeRlMNCl5GTzU0MCw4NV5BRE4sMTIsNl5GRE5ldCBDaGc6IDExLjYzXkZTDQpeRk8yMTAsMTEwXkFETiwxMiw2XkZEU3ZjczogIEdyb3VuZF5GUw0KXkZPMjQwLDEzMF5BRE4sMTIsNl5GRFRSQ0s6IDFaMlZZOTEyMDMwMDAwMzAxM15GUw0KXlhaXlhaCg==";

        public Bitmap           label;
        public Graphics         graphics;
        public Brush            brush;
        public Pen              pen;
        public List<String>     err                 =new List<string>();
        public string           position_mode       ="";
        public int              _dpi                =203;                   //152,203,300,608 dpi
        public Rectangle        label_bounds        =new Rectangle();       //offset+width/height of label
        public bool             use_titan_engine    =true;
        public bool             redraw              =true;
        public void titanZPL_variables() {
            brush=Brushes.Black;
            pen=Pens.Black;
            label_bounds.Width=800;
            label_bounds.Height=600;
        }//end init

        public titanZPL() {
            titanZPL_variables();
        }

        public titanZPL(string data) {
            titanZPL_variables();
            load_document(data);
            build();
            draw();
        }

        public void set_label_type(float w,float h,float dpi) {
            label_bounds.Width =(int)(w*dpi);
            label_bounds.Height=(int)(h*dpi);
            _dpi=(int)dpi;
        }

        public void test_zpl() {
            //build_raster_fonts_from_printer.generate_raster_fonts();
            load_document(zpl_data_base64);   
            build();
            draw();
        }

        public void load(string zpl) {
            load_document(zpl);   
            build();
            draw();
        }
    }//end class
}//end namespace
