/*****************************************************************************
*       ████████╗██╗████████╗ █████╗ ███╗   ██╗███████╗██████╗ ██╗           *
*       ╚══██╔══╝██║╚══██╔══╝██╔══██╗████╗  ██║╚══███╔╝██╔══██╗██║           *
*          ██║   ██║   ██║   ███████║██╔██╗ ██║  ███╔╝ ██████╔╝██║           *
*          ██║   ██║   ██║   ██╔══██║██║╚██╗██║ ███╔╝  ██╔═══╝ ██║           *
*          ██║   ██║   ██║   ██║  ██║██║ ╚████║███████╗██║     ███████╗      *
*          ╚═╝   ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚═╝     ╚══════╝      *
******************************************************************************
*      Created By: Charles Watkins                                           *
*      Date      : 2017-10-12                                                *
*****************************************************************************/
using System;
using System.Collections.Generic;
namespace titanZPL.commands  {
    public class zpl_cmd_t_DS : zpl_command{   //Download Intellifont (Scalable Font)
        public string device_to_store_image                                        = String.Empty;
        public string image_name                                                   = String.Empty;
        public string extension_fixed_value                                        = String.Empty;
        public string s                                                            = String.Empty;
        public string data                                                         = String.Empty;
                                        
        public zpl_cmd_t_DS(string data,List<zpl_command> commands):base(commands){                    
            cmd        ="~DS";                   
            description="Download Intellifont (Scalable Font)";                   
            data_format="d,o,x,s,data ";                   
            example    ="";                   
            device_to_store_image                                       =(string)argument(0,data,"s","                   ",""," ");
            image_name                                                  =(string)argument(1,data,"s","                   ",""," ");
            extension_fixed_value                                       =(string)argument(2,data,"s","                   ",""," ");
            s                                                           =(string)argument(3,data,"s","                   ",""," ");
            data                                                        =(string)argument(4,data,"s","                   ",""," ");
                                    
  /*************************************************  
	
d =device_to_store_image //R:, E:, B:, and A:  //R: 
	
o =image_name //1 to 8 alphanumeric characters  //if a name is not specified, UNKNOWN is used 
	
x =extension_Fixed_Value // //-
                                       
  **************************************************/ 
            manual=""+ 
			"~DS – Download Intellifont (Scalable Font) "+ 
			"The ~DS command is used to set the printer to receive a downloadable scalable font and defines the "+ 
			"size of the font in bytes. "+ 
			"The "+ 
			"~DS command, and its associated parameters, is the result of converting a vendor-supplied font "+ 
			"for use on a Zebra printer. To convert this font use the ZTools utility. "+ 
			"Format: ~DSd:o.x,s,data "+ 
			"Comments Downloaded scalable fonts are not checked for integrity. If they are corrupt, "+ 
			"they cause unpredictable results at the printer. "+ 
			"Parameters Details "+ 
			"d = device to store "+ 
			"image "+ 
			"Values: R:, E:, B:, and A: "+ 
			"Default: R: "+ 
			"o = image name "+ 
			"Values: 1 to 8 alphanumeric characters "+ 
			"Default: if a name is not specified, UNKNOWN is used "+ 
			"x = extension Fixed Value: .FNT "+ 
			"s = size of font in "+ 
			"bytes "+ 
			"Fixed Value: this number is generated by ZTools and should "+ 
			"not be changed "+ 
			"data = ASCII "+ 
			"hexadecimal "+ 
			"string that "+ 
			"defines font "+ 
			"Fixed Value: this number is generated by ZTools and should "+ 
			"not be changed "+ 
			"Example: This example shows the first three lines of a scalable font that was converted using the "+ 
			"ZTools program and is ready to be downloaded to the printer. If necessary, the destination and object "+ 
			"name can be changed. "+ 
			"~DSB:CGTIMES.FNT,37080, "+ 
			"OOFFOOFFOOFFOOFF "+ 
			"FFOAECB28FFFOOFF "+ 
			"If you are using a TrueType font use these commands: ~DT, ~DU, and ~DY. To determine "+ 
			"when to use the noted commands, see ~DT on page 154, ~DU on page 155, and ~DY "+ 
			"on page 156. "+ 
			" "+ 
			"ZPL Commands "+ 
			"~DT "+ 
			"154 "+ 
			"P1012728-011 Zebra Programming Guide 11/21/16 ";                           
        }//end init function                      
    }//end class                                  
}//end namespace                                  
